//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopTools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceMain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMain() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShopTools.ResourceMain", typeof(ResourceMain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:\s*(?&lt;angle&gt;-{0,1}[0-9]+(\.[0-9]+){0,1})\s*(?&lt;unit&gt;[a-z]*)).
        /// </summary>
        internal static string rxAngleUnit {
            get {
                return ResourceManager.GetString("rxAngleUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;fractional&gt;(((?&lt;number&gt;-{0,1}[0-9]+\s+){0,1}(?&lt;fraction&gt;(?&lt;numerator&gt;[0-9]+)\s*/\s*(?&lt;denominator&gt;[0-9]+)))|(?&lt;number&gt;-{0,1}[0-9]+(\.{0,1}[0-9]+){0,1}))).
        /// </summary>
        internal static string rxFractional {
            get {
                return ResourceManager.GetString("rxFractional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \{(?&lt;variable&gt;[^\:\}]+)(\:(?&lt;format&gt;[^\}]*)){0,1}\}.
        /// </summary>
        internal static string rxInterpolatedVariableAndFormat {
            get {
                return ResourceManager.GetString("rxInterpolatedVariableAndFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:\s*(?&lt;numeric&gt;(-{0,1}([0-9]+\s+){0,1}[0-9]+\s*/\s*[0-9]+)|(-{0,1}[0-9]*(\.{0,1}[0-9]+){0,1}))\s*(?&lt;nonnumeric&gt;[&apos;\&quot;]|[a-z]*)).
        /// </summary>
        internal static string rxNumericNonNumeric {
            get {
                return ResourceManager.GetString("rxNumericNonNumeric", resourceCulture);
            }
        }
    }
}
