//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopTools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceMain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMain() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShopTools.ResourceMain", typeof(ResourceMain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CutEllipseIcon.png,CutLineIcon.png,CutRectangleIcon.png,CutTwoLineIcon.png,DrillHoleIcon.png,EuroHingeCupIcon01.png,MoveWithoutCuttingIcon.png,NoImageIcon.png.
        /// </summary>
        internal static string BuiltInPatternImageNames {
            get {
                return ResourceManager.GetString("BuiltInPatternImageNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright© 2024 - 2025 Daniel Patterson, MCSD (danielanywhere).
        /// </summary>
        internal static string CopyrightMessage {
            get {
                return ResourceManager.GetString("CopyrightMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:\s*(?&lt;angle&gt;-{0,1}[0-9]+(\.[0-9]+){0,1})\s*(?&lt;unit&gt;[a-z]*)).
        /// </summary>
        internal static string rxAngleUnit {
            get {
                return ResourceManager.GetString("rxAngleUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?m:^(?&lt;data&gt;data\:)(?&lt;mimeType&gt;[^;]+);(?&lt;base&gt;base64,)).
        /// </summary>
        internal static string rxDataUriHeader {
            get {
                return ResourceManager.GetString("rxDataUriHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;fraction&gt;(?&lt;numerator&gt;\d+)/(?&lt;denominator&gt;\d+)).
        /// </summary>
        internal static string rxFraction {
            get {
                return ResourceManager.GetString("rxFraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;fractional&gt;(((?&lt;number&gt;-{0,1}[0-9]+\s+){0,1}(?&lt;fraction&gt;(?&lt;numerator&gt;[0-9]+)\s*/\s*(?&lt;denominator&gt;[0-9]+)))|(?&lt;number&gt;-{0,1}[0-9]+(\.{0,1}[0-9]+){0,1}))).
        /// </summary>
        internal static string rxFractional {
            get {
                return ResourceManager.GetString("rxFractional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \(Filename:(?&lt;filename&gt;[^\)]+)\).
        /// </summary>
        internal static string rxGCodeRemarkEmbeddedFilename {
            get {
                return ResourceManager.GetString("rxGCodeRemarkEmbeddedFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \{(?&lt;variable&gt;[^\:\}]+)(\:(?&lt;format&gt;[^\}]*)){0,1}\}.
        /// </summary>
        internal static string rxInterpolatedVariableAndFormat {
            get {
                return ResourceManager.GetString("rxInterpolatedVariableAndFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:(?&lt;fraction&gt;(?&lt;numerator&gt;\d+)/(?&lt;denominator&gt;\d+))|(?&lt;numeric&gt;(-{0,1}(([0-9]+\.[0-9]+)|[0-9]+|\.[0-9]+)))|(?&lt;symbol&gt;\*|/|\+|\-|\^|\%)|(?&lt;paren&gt;\(|\))|(?&lt;unit&gt;[&apos;\&quot;]|[a-z]+)).
        /// </summary>
        internal static string rxMeasurementExpression {
            get {
                return ResourceManager.GetString("rxMeasurementExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:\s*(?&lt;numeric&gt;(-{0,1}([0-9]+\s+){0,1}[0-9]+\s*/\s*[0-9]+)|(-{0,1}[0-9]*(\.{0,1}[0-9]+){0,1}))\s*(?&lt;nonnumeric&gt;[&apos;\&quot;]|[a-z]*)).
        /// </summary>
        internal static string rxNumericNonNumeric {
            get {
                return ResourceManager.GetString("rxNumericNonNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ((?&lt;word&gt;[^\s]+)(?&lt;space&gt;[ \t]*))|(?&lt;lineend&gt;\r{0,1}\n).
        /// </summary>
        internal static string rxWordSpace {
            get {
                return ResourceManager.GetString("rxWordSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ToolPin2445 {
            get {
                object obj = ResourceManager.GetObject("ToolPin2445", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UpTextIcon {
            get {
                object obj = ResourceManager.GetObject("UpTextIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
